Styles improvements and binary deletion
fucomp/fucomp.github.io pull request #8
Opened 2016-10-15 20:48 UTC by badsectortv

2016-10-15 21:05 UTC, oholiab requested changes
Can you flatten the commits so that the image file doesn't turn up at all? Otherwise it's going to weedle its way into commit history despite the fact it's never been on HEAD

2016-10-15 21:31 UTC, badsectortv commented
I am unsure of how to do that.

On 15 October 2016 22:05:46 BST, Matt Carroll <notifications@github.com> wrote:
>oholiab requested changes on this pull request.
>
>Can you flatten the commits so that the image file doesn't turn up at
>all? Otherwise it's going to weedle its way into commit history despite
>the fact it's never been on HEAD
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fucomp/fucomp.github.io/pull/8#pullrequestreview-4379626

-- 
B3F3 AFFD 0EC7 D6EB ED72
710D 11C2 AF68 B998 8A85

2016-10-17 19:37 UTC, badsectortv commented
@oholiab - how do we do this?

2016-10-24 19:58 UTC, oholiab approved these changes

2016-10-24 19:59 UTC, merged